import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import { Plus, Edit, AlertTriangle, Copy, RefreshCw, Check } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import { generateCustomerCode, sanitizeCustomerCode, makeCodeUnique } from "@/lib/customerCode";
import { cn } from "@/lib/utils";

interface Customer {
  id?: string;
  name: string;
  email: string;
  phone: string;
  vat_number: string;
  address_line1: string;
  address_line2: string;
  locality: string;
  post_code: string;
  payment_terms: string;
  vat_status: string;
  client_type: string;
  business_name: string;
  notes: string;
  date_added?: string;
  customer_code?: string;
}

interface CustomerFormProps {
  customer?: Customer;
  onSave: () => void;
  trigger?: React.ReactNode;
}

export function CustomerForm({ customer, onSave, trigger }: CustomerFormProps) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();
  const { user } = useAuth();
  
  const [formData, setFormData] = useState<Customer>({
    name: customer?.name || "",
    email: customer?.email || "",
    phone: customer?.phone || "",
    vat_number: customer?.vat_number || "",
    address_line1: customer?.address_line1 || "",
    address_line2: customer?.address_line2 || "",
    locality: customer?.locality || "",
    post_code: customer?.post_code || "",
    payment_terms: customer?.payment_terms || "Net 30",
    vat_status: customer?.vat_status || "",
    client_type: customer?.client_type || "Individual",
    business_name: customer?.business_name || "",
    notes: customer?.notes || "",
    customer_code: customer?.customer_code || "",
  });

  const [showVatWarning, setShowVatWarning] = useState(false);
  const [codeMode, setCodeMode] = useState<'auto' | 'custom'>('auto');
  const [codeError, setCodeError] = useState<string | null>(null);
  const [existingCodes, setExistingCodes] = useState<string[]>([]);
  const [copied, setCopied] = useState(false);
  const [regenerateKey, setRegenerateKey] = useState(0);

  useEffect(() => {
    if (open && user) {
      fetchExistingCodes();
    }
  }, [open, user]);

  const fetchExistingCodes = async () => {
    if (!user) return;
    const { data } = await supabase
      .from("customers")
      .select("customer_code")
      .eq("user_id", user.id)
      .not("customer_code", "is", null);
    
    const codes = (data || [])
      .map(c => c.customer_code)
      .filter((code): code is string => code !== null);
    setExistingCodes(codes);
  };

  const autoGeneratedCode = generateCustomerCode(
    formData.name,
    formData.client_type === "Business" ? formData.business_name : undefined
  );

  const uniqueAutoCode = makeCodeUnique(autoGeneratedCode, existingCodes);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.vat_status) {
      setShowVatWarning(true);
    } else {
      setShowVatWarning(false);
    }
    
    setLoading(true);
    setCodeError(null);

    try {
      let finalCode: string;
      if (codeMode === 'auto') {
        finalCode = uniqueAutoCode;
      } else {
        finalCode = formData.customer_code || '';
      }

      if (!finalCode) {
        setCodeError("Customer code is required");
        setLoading(false);
        return;
      }

      if (codeMode === 'custom' && existingCodes.includes(finalCode)) {
        setCodeError("This customer code is already in use");
        setLoading(false);
        return;
      }

      if (customer?.id) {
        const { error } = await supabase
          .from("customers")
          .update({ ...formData, customer_code: finalCode })
          .eq("id", customer.id);

        if (error) throw error;
        
        toast({
          title: "Customer updated",
          description: "Customer information has been successfully updated.",
        });
      } else {
        if (!user?.id) {
          throw new Error("User not authenticated");
        }
        
        const { error } = await supabase
          .from("customers")
          .insert([{ ...formData, customer_code: finalCode, user_id: user.id }]);

        if (error) {
          if (error.code === '23505' && error.message.includes('customer_code')) {
            setCodeError("This customer code is already in use");
            setLoading(false);
            return;
          }
          throw error;
        }
        
        toast({
          title: "Customer created",
          description: "New customer has been successfully added.",
        });
      }

      setOpen(false);
      onSave();
      
      if (!customer?.id) {
        setFormData({
          name: "",
          email: "",
          phone: "",
          vat_number: "",
          address_line1: "",
          address_line2: "",
          locality: "",
          post_code: "",
          payment_terms: "Net 30",
          vat_status: "",
          client_type: "Individual",
          business_name: "",
          notes: "",
          customer_code: "",
        });
        setShowVatWarning(false);
        setCodeMode('auto');
        setCodeError(null);
      }
    } catch (error) {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "An error occurred",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleCustomCodeChange = (value: string) => {
    const sanitized = sanitizeCustomerCode(value);
    setFormData({ ...formData, customer_code: sanitized });
    setCodeError(null);
  };

  const handleCopyCode = async () => {
    const code = codeMode === 'auto' ? uniqueAutoCode : formData.customer_code;
    if (code) {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleRegenerate = () => {
    setRegenerateKey(prev => prev + 1);
  };

  const defaultTrigger = customer?.id ? (
    <Button variant="ghost" size="sm">
      <Edit className="h-4 w-4" />
    </Button>
  ) : (
    <Button size="sm">
      <Plus className="h-4 w-4 mr-2" />
      New Customer
    </Button>
  );

  const SectionHeader = ({ children }: { children: React.ReactNode }) => (
    <div className="space-y-2">
      <h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
        {children}
      </h4>
      <Separator className="bg-border/60" />
    </div>
  );

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || defaultTrigger}
      </DialogTrigger>
      <DialogContent className="sm:max-w-[640px] max-h-[90vh] p-0 flex flex-col overflow-hidden">
        <DialogHeader className="px-6 pt-6 pb-4">
          <DialogTitle className="text-lg font-semibold">
            {customer?.id ? "Edit Customer" : "New Customer"}
          </DialogTitle>
        </DialogHeader>
        
        <form onSubmit={handleSubmit} className="flex flex-col flex-1 overflow-hidden">
          <div className="flex-1 overflow-y-auto px-6 pb-4">
            <div className="space-y-6">
              
              {/* Client Type Section */}
              <div className="space-y-3">
                <SectionHeader>Client Type</SectionHeader>
                <div className="space-y-4">
                  <div className="inline-flex rounded-lg border border-input p-1 bg-muted/30">
                    <button
                      type="button"
                      onClick={() => setFormData({ ...formData, client_type: "Individual" })}
                      className={cn(
                        "px-4 py-1.5 text-sm font-medium rounded-md transition-all",
                        formData.client_type === "Individual"
                          ? "bg-background text-foreground shadow-sm"
                          : "text-muted-foreground hover:text-foreground"
                      )}
                    >
                      Individual
                    </button>
                    <button
                      type="button"
                      onClick={() => setFormData({ ...formData, client_type: "Business" })}
                      className={cn(
                        "px-4 py-1.5 text-sm font-medium rounded-md transition-all",
                        formData.client_type === "Business"
                          ? "bg-background text-foreground shadow-sm"
                          : "text-muted-foreground hover:text-foreground"
                      )}
                    >
                      Business
                    </button>
                  </div>
                  
                  {formData.client_type === "Business" && (
                    <div className="space-y-1.5">
                      <Label htmlFor="business_name" className="text-sm">Business Name *</Label>
                      <Input
                        id="business_name"
                        value={formData.business_name}
                        onChange={(e) => setFormData({ ...formData, business_name: e.target.value })}
                        required={formData.client_type === "Business"}
                        placeholder="Acme Corporation"
                        className="h-9"
                      />
                    </div>
                  )}
                </div>
              </div>

              {/* Contact Details Section */}
              <div className="space-y-3">
                <SectionHeader>Contact Details</SectionHeader>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label htmlFor="name" className="text-sm">Name *</Label>
                    <Input
                      id="name"
                      value={formData.name}
                      onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                      required
                      placeholder="John Doe"
                      className="h-9"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="email" className="text-sm">Email</Label>
                    <Input
                      id="email"
                      type="email"
                      value={formData.email}
                      onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                      placeholder="john@example.com"
                      className="h-9"
                    />
                  </div>
                  <div className="space-y-1.5 md:col-span-2">
                    <Label htmlFor="phone" className="text-sm">Phone</Label>
                    <Input
                      id="phone"
                      value={formData.phone}
                      onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                      placeholder="+356 9999 0000"
                      className="h-9"
                    />
                  </div>
                </div>
              </div>

              {/* Address Section */}
              <div className="space-y-3">
                <SectionHeader>Address</SectionHeader>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label htmlFor="address_line1" className="text-sm">House/No.</Label>
                    <Input
                      id="address_line1"
                      value={formData.address_line1}
                      onChange={(e) => setFormData({ ...formData, address_line1: e.target.value })}
                      placeholder="123 / Villa"
                      className="h-9"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="address_line2" className="text-sm">Street</Label>
                    <Input
                      id="address_line2"
                      value={formData.address_line2}
                      onChange={(e) => setFormData({ ...formData, address_line2: e.target.value })}
                      placeholder="Republic St"
                      className="h-9"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="locality" className="text-sm">Locality</Label>
                    <Input
                      id="locality"
                      value={formData.locality}
                      onChange={(e) => setFormData({ ...formData, locality: e.target.value })}
                      placeholder="Valletta"
                      className="h-9"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="post_code" className="text-sm">Post Code</Label>
                    <Input
                      id="post_code"
                      value={formData.post_code}
                      onChange={(e) => setFormData({ ...formData, post_code: e.target.value })}
                      placeholder="VLT 1234"
                      className="h-9"
                    />
                  </div>
                </div>
              </div>

              {/* Customer Code Section */}
              <div className="space-y-3">
                <SectionHeader>Customer Code</SectionHeader>
                <Tabs value={codeMode} onValueChange={(v) => { setCodeMode(v as 'auto' | 'custom'); setCodeError(null); }} className="w-full">
                  <TabsList className="grid w-full max-w-[200px] grid-cols-2 h-8">
                    <TabsTrigger value="auto" className="text-xs">Auto</TabsTrigger>
                    <TabsTrigger value="custom" className="text-xs">Custom</TabsTrigger>
                  </TabsList>
                  
                  <TabsContent value="auto" className="mt-3 space-y-2">
                    <div className="flex items-center gap-2">
                      <div className="relative flex-1">
                        <Input
                          value={uniqueAutoCode}
                          readOnly
                          className="h-9 font-mono text-sm tracking-wider bg-muted/50 pr-10"
                        />
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={handleCopyCode}
                          className="absolute right-1 top-1/2 -translate-y-1/2 h-7 w-7 p-0"
                        >
                          {copied ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5 text-muted-foreground" />}
                        </Button>
                      </div>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={handleRegenerate}
                        className="h-9 px-3"
                      >
                        <RefreshCw className="h-3.5 w-3.5" />
                      </Button>
                    </div>
                  </TabsContent>
                  
                  <TabsContent value="custom" className="mt-3 space-y-2">
                    <div className="relative">
                      <Input
                        value={formData.customer_code}
                        onChange={(e) => handleCustomCodeChange(e.target.value)}
                        placeholder="CUST001"
                        maxLength={10}
                        className={cn(
                          "h-9 font-mono text-sm tracking-wider uppercase pr-16",
                          codeError && "border-destructive focus-visible:ring-destructive"
                        )}
                      />
                      <span className="absolute right-3 top-1/2 -translate-y-1/2 text-[10px] text-muted-foreground tabular-nums">
                        {formData.customer_code?.length || 0}/10
                      </span>
                    </div>
                    {codeError ? (
                      <p className="text-xs text-destructive">{codeError}</p>
                    ) : (
                      <p className="text-xs text-muted-foreground">A–Z and 0–9 only. No spaces. Must be unique.</p>
                    )}
                  </TabsContent>
                </Tabs>
                <p className="text-xs text-muted-foreground">Locked after the first issued invoice.</p>
              </div>

              {/* VAT Section - Only show for Business */}
              {formData.client_type === "Business" && (
                <div className="space-y-3">
                  <SectionHeader>VAT Information</SectionHeader>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label htmlFor="vat_number" className="text-sm">VAT Number</Label>
                      <Input
                        id="vat_number"
                        value={formData.vat_number}
                        onChange={(e) => setFormData({ ...formData, vat_number: e.target.value })}
                        placeholder="MT12345678"
                        className="h-9"
                      />
                    </div>
                    <div className="space-y-1.5">
                      <Label htmlFor="vat_status" className="text-sm">VAT Status</Label>
                      <Select
                        value={formData.vat_status}
                        onValueChange={(value) => {
                          setFormData({ ...formData, vat_status: value });
                          setShowVatWarning(false);
                        }}
                      >
                        <SelectTrigger className="h-9">
                          <SelectValue placeholder="Select status" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="Standard (18%)">Standard (18%)</SelectItem>
                          <SelectItem value="Exempt">Exempt</SelectItem>
                          <SelectItem value="Reverse Charge">Reverse Charge</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  {showVatWarning && (
                    <div className="flex items-center gap-2 text-sm text-amber-600 dark:text-amber-500">
                      <AlertTriangle className="h-4 w-4 shrink-0" />
                      <span>VAT status not selected.</span>
                    </div>
                  )}
                </div>
              )}

              {/* Payment Terms */}
              <div className="space-y-3">
                <SectionHeader>Payment Terms</SectionHeader>
                <div className="space-y-1.5 max-w-xs">
                  <Select
                    value={formData.payment_terms}
                    onValueChange={(value) => setFormData({ ...formData, payment_terms: value })}
                  >
                    <SelectTrigger className="h-9">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Net 7">Net 7</SelectItem>
                      <SelectItem value="Net 30">Net 30</SelectItem>
                      <SelectItem value="Due on receipt">Due on receipt</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {/* Notes */}
              <div className="space-y-3">
                <SectionHeader>Notes</SectionHeader>
                <Textarea
                  id="notes"
                  value={formData.notes}
                  onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                  rows={2}
                  placeholder="Internal notes..."
                  className="resize-none text-sm"
                />
              </div>

              {/* Date Added (Read-only for edit) */}
              {customer?.date_added && (
                <div className="pt-2">
                  <p className="text-xs text-muted-foreground">
                    Added on {new Date(customer.date_added).toLocaleDateString()}
                  </p>
                </div>
              )}
            </div>
          </div>

          {/* Sticky Footer */}
          <div className="flex items-center justify-between gap-3 px-6 py-4 border-t border-border bg-background">
            <Button
              type="button"
              variant="outline"
              onClick={() => setOpen(false)}
              disabled={loading}
              className="h-9"
            >
              Cancel
            </Button>
            <Button type="submit" disabled={loading} className="h-9">
              {loading ? "Saving..." : customer?.id ? "Update Customer" : "Create Customer"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
